name: mobile_attendance
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  latlong2: ^0.9.1
  sqflite: ^2.3.3+1
  syncfusion_flutter_maps: ^26.2.9

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
